spring.application.name=RiskMod


# --- MySQL Database Connection ---
spring.datasource.url=jdbc:mysql://localhost:3306/riskmod_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# --- JPA & Hibernate Settings ---
# This is a crucial setting for development.
# "update" tells Hibernate to automatically create or update your tables
# based on your @Entity classes (User, Portfolio, Asset).
spring.jpa.hibernate.ddl-auto=update

# This is great for debugging. It will print every SQL query
# that Spring runs to the console.
spring.jpa.show-sql=true

# --- External API Keys ---
alphavantage.api.key=0NK4QW8OFUTJ3U6I